version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xubangjun886
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  java-app:
    build:
      context: ./  # 指定 Dockerfile 所在的目录
      dockerfile: Dockerfile  # 可选项，默认寻找 `Dockerfile`
    depends_on:
      - postgres
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: xubangjun886
      DB_NAME: postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
